In [18]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from wordcloud import WordCloud
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [2]:
df = pd.read_csv('D:/Data Analysis/Space Mission Analysis/Dataset/Space_Missions_Dataset.csv')

In [3]:
df['Launch_Year'] = df['Launch_Date'].str.split("-").str[0]

In [5]:
df.isnull().sum()

Mission_ID                   0
Mission_Name                 0
Agency                       0
Country_Region               0
Agency_Type                  0
Program_Type                 0
Mission_Category             0
Sub_Category                 0
Launch_Date                  0
End_Date                  4704
Duration                   234
Launch_Vehicle               0
Launch_Site                  0
Status                       0
Mission_Phase                0
Crew_Type                    0
Crew_Members              7863
Destination                  0
Objective                    0
Key_Achievement            321
Cost_USD_Million             0
Partner_Agencies          6164
Data_Returned             1560
Failure_Reason            9339
Mission_Outcome_Detail       0
Reference_URL                0
Launch_Year                  0
dtype: int64

In [4]:
df.columns

Index(['Mission_ID', 'Mission_Name', 'Agency', 'Country_Region', 'Agency_Type',
       'Program_Type', 'Mission_Category', 'Sub_Category', 'Launch_Date',
       'End_Date', 'Duration', 'Launch_Vehicle', 'Launch_Site', 'Status',
       'Mission_Phase', 'Crew_Type', 'Crew_Members', 'Destination',
       'Objective', 'Key_Achievement', 'Cost_USD_Million', 'Partner_Agencies',
       'Data_Returned', 'Failure_Reason', 'Mission_Outcome_Detail',
       'Reference_URL', 'Launch_Year'],
      dtype='object')

In [ ]:
required_columns = ["Mission_Name","Agency","Country_Region","Agency_Type","Mission_Category","Launch_Vehicle","Status","Mission_Phase","Crew_Type","Objective","Mission_Outcome_Detail","Destination","Cost_USD_Million","Launch_Year"]
df1 = df[required_columns]

In [13]:
df1.isnull().sum()

Mission_Name              0
Agency                    0
Country_Region            0
Agency_Type               0
Mission_Category          0
Launch_Vehicle            0
Status                    0
Mission_Phase             0
Crew_Type                 0
Objective                 0
Mission_Outcome_Detail    0
Cost_USD_Million          0
Launch_Year               0
dtype: int64

In [12]:
df1.head()

,Mission_Name,Agency,Country_Region,Agency_Type,Mission_Category,Launch_Vehicle,Status,Mission_Phase,Crew_Type,Objective,Mission_Outcome_Detail,Cost_USD_Million,Launch_Year
0,Explorer 1,NASA,USA,Government,Mercury,Pegasus,Failed,Past,Uncrewed,Black hole imaging and stellar cataloguing,Exceeded planned science return by 3x,7708.6,1976
1,Pioneer 1,NASA,USA,Government,Saturn,Saturn V,Success,Past,Uncrewed,Orbital mechanics experiment for future missions,Detected organic molecules at surface,11802.2,1977
2,Mercury-Redstone 1,NASA,USA,Government,Earth Observation,Pegasus,Failed,Past,Crewed,Gamma-ray burst detection and cataloguing,Planned - objectives to be confirmed post-launch,7836.7,1966
3,Freedom 7,NASA,USA,Government,Mercury,Titan,Success,Past,Uncrewed,Earth observation for disaster management,Failed to achieve orbit due to launch vehicle ...,10659.5,1987
4,Friendship 7,NASA,USA,Government,Telescope,SLS,Ongoing,Past,Uncrewed,Human lunar landing mission support,Detected organic molecules at surface,4385.5,2012

In [ ]:
df1['combined'] = df1['Agency'] + ' ' + df1['Country_Region'] + ' ' +df1['Agency_Type'] + ' ' + df1['Mission_Category'] + ' ' + df1['Launch_Vehicle'] + ' ' +  df1['Status'] + ' ' + df1['Mission_Phase'] + ' ' + df1['Crew_Type'] + ' ' + df1['Objective'] + ' ' + df1['Destination'] + ' ' + df1['Mission_Outcome_Detail'] 

df1['combined']

C:\Users\ASHUTOSH\AppData\Local\Temp\ipykernel_15796\356456174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['combined'] = df1['Agency'] + ' ' + df1['Country_Region'] + ' ' +df1['Agency_Type'] + ' ' + df1['Mission_Category'] + ' ' + df1['Launch_Vehicle'] + ' ' +  df1['Status'] + ' ' + df1['Mission_Phase'] + ' ' + df1['Crew_Type'] + ' ' + df1['Objective'] + ' ' + df1['Mission_Outcome_Detail']

0        NASA USA Government Mercury Pegasus Failed Pas...
1        NASA USA Government Saturn Saturn V Success Pa...
2        NASA USA Government Earth Observation Pegasus ...
3        NASA USA Government Mercury Titan Success Past...
4        NASA USA Government Telescope SLS Ongoing Past...
                               ...
10495    CSA Canada Government CubeSat Delta II Ongoing...
10496    CNES France Government Asteroid Diamant Succes...
10497    CNSA China Government Venus Long March 9 Succe...
10498    CNSA China Government Deep Space Long March 2 ...
10499    CNSA China Government Sun/Solar Long March 3 O...
Name: combined, Length: 10500, dtype: object

In [16]:
data  = df1[['Mission_Name','combined','Cost_USD_Million','Launch_Year']]
data.head()

,Mission_Name,combined,Cost_USD_Million,Launch_Year
0,Explorer 1,NASA USA Government Mercury Pegasus Failed Pas...,7708.6,1976
1,Pioneer 1,NASA USA Government Saturn Saturn V Success Pa...,11802.2,1977
2,Mercury-Redstone 1,NASA USA Government Earth Observation Pegasus ...,7836.7,1966
3,Freedom 7,NASA USA Government Mercury Titan Success Past...,10659.5,1987
4,Friendship 7,NASA USA Government Telescope SLS Ongoing Past...,4385.5,2012

In [19]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))


def preprocess_text(text):
    # Remove special characters and numbers
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    # Convert to lowercase
    text = text.lower()
    # Tokenize and remove stopwords
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt_tab: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

In [21]:
data['cleaned_text'] = df1['combined'].apply(preprocess_text)

C:\Users\ASHUTOSH\AppData\Local\Temp\ipykernel_15796\4120873995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['cleaned_text'] = df1['combined'].apply(preprocess_text)

In [22]:
tfidf = TfidfVectorizer(max_features=5000)
tfidf_matrix = tfidf.fit_transform(data['cleaned_text'])

cosine_sim = cosine_similarity(tfidf_matrix,tfidf_matrix)

In [27]:
def recommend_missions(mission_name, cosine_sim=cosine_sim, df=data, top_n=5):
    # Find the index of the movie
    idx = df[df['Mission_Name'].str.lower() == mission_name.lower()].index
    if len(idx) == 0:
        return "Mission not found in the dataset!"
    idx = idx[0]

    # Get similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]

    # Get movie indices
    mission_indices = [i[0] for i in sim_scores]

    # Return top n similar movies
    return df[['Mission_Name']].iloc[mission_indices]

In [24]:
df['Mission_Name'].value_counts()

Mission_Name
CRS-10                          2
Crew-7                          2
Mars Express                    2
CRS-30                          2
CRS-25                          2
                               ..
CNES Sun/Solar Mission 3532     1
NASA Deep Space Mission 3533    1
CNSA Sun/Solar Mission 3534     1
DLR Mars Mission 3535           1
CNSA Sun/Solar Mission 10500    1
Name: count, Length: 10477, dtype: int64

In [32]:
recommendations = recommend_missions('Aryabhata')
print(recommendations)

                            Mission_Name
9267       ISRO Earth Orbit Mission 9268
6302          ISRO SmallSat Mission 6303
8543  CSA Earth Observation Mission 8544
2788            ISRO Saturn Mission 2789
4313            ISRO Saturn Mission 4314

In [30]:
df[df['Mission_Name'] == 'Falcon Heavy ARABSAT']

,Mission_ID,Mission_Name,Agency,Country_Region,Agency_Type,Program_Type,Mission_Category,Sub_Category,Launch_Date,End_Date,...,Destination,Objective,Key_Achievement,Cost_USD_Million,Partner_Agencies,Data_Returned,Failure_Reason,Mission_Outcome_Detail,Reference_URL,Launch_Year
899,SP-00900,Falcon Heavy ARABSAT,SpaceX,USA,Private,Satellite,ISS,Cargo Resupply,1961-01-07,1968-03-06,...,ISS,Jupiter moon subsurface ocean investigation,Broke distance record for agency,8100.6,NASA,No,Partial instrument failure,Collected and returned surface samples,https://www.spacex.com/missions/falcon-heavy-a...,1961

In [31]:
df[df['Agency'] == 'ISRO']['Mission_Name'].value_counts()

Mission_Name
Aryabhata                                     1
ISRO Saturn Mission 7067                      1
ISRO Asteroid Mission 6784                    1
ISRO Jupiter Mission 6789                     1
ISRO Sun/Solar Mission 6790                   1
                                             ..
ISRO Mars Mission 3738                        1
ISRO Mercury Mission 3750                     1
ISRO SmallSat Mission 3753                    1
ISRO Mercury Mission 3771                     1
ISRO Communication Satellite Mission 10452    1
Name: count, Length: 840, dtype: int64